### ISSUE TITLE
Divide page into personal and professional

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#100]
I would like to split the page into a personal and a professional area.
The professional area should be the default homepage (index.hbs) and contain only posts with the first tag "Pro".
The personal area should be accessible at /personal and contain everything EXCEPT posts with the tag "Pro".
I tried to duplicate the index.hbs and add something like
`{{#get "posts" filter="-[Pro]"}}{{/get}}` before the line `{{> "loop"}}` ([source](https://www.jackwdavis.com/how-to-exclude-tags-from-the-ghost-homepage/)) but that didn't work.
How can I do it?
Thanks in advance.

**Comment by godofredoninja** [comment]
Hi @MaluNoPeleke 

I think you can do better with the [routes](https://docs.ghost.org/faq/filter-property-routes-yaml/) and [internal tag](https://docs.ghost.org/concepts/tags/#internal-tag)

To your articles add an internal tag for example `#pro`

Then you have to make a backup of your routes

`Ghost Admin -> Labs -> Routes`

then make a copy to the `routes.yml` and edit similar to this

```yaml
routes:

collections:
  /:
    #permalink: /{year}/{month}/{day}/{slug}/
    filter: tag:[hash-pro] # internal tag -> #pro
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

Then you tell me if this solution is right for you. Or you need other alternatives.

**Comment by MaluNoPeleke** [comment]
Thanks for the quick support.
I tried it with the following routes.yaml but nothing happened after I uploaded it:

```
routes:

collections:
  /:
    filter: primary_tag:pro
    permalink: /{slug}/
    template: index

  /personal/:
    filter: primary_tag:-pro
    permalink: /{slug}/

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

**Comment by godofredoninja** [comment]
I just checked and everything's working fine.

If you can't see changes, it's possible to restart ghost

` ghost restart`

**Comment by MaluNoPeleke** [comment]
It is working with channels like this but I would like to use the index template for the homepage (/) and the masonry (home) template for the /pro/ channel.
That is why I renamed the home.hbs to pro.hbs and added this to the routes.yaml:

```
routes:
  /professional/:
    controller: channel
    filter: tag:[pro,ux]
    template: pro
    order: published_at desc

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

Still the /pro/ URL is using the index.hbs template.

**Comment by godofredoninja** [comment]
Hello @MaluNoPeleke  😄 

I just created a new branch for your project.
this branch has some modifications.

— And everything works perfect

https://github.com/godofredoninja/Mapache/tree/frederik

— `routes.yml`
```yaml
routes:
  /professional/:
    controller: channel
    filter: tag:[pro,ux]
    template: pro
    order: published_at desc

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
---

### If you want to change the title of professional page. you have to do the following.

1. Create a Page
2. In Page URL  use `professional`
3. new `routes.yml`

```yaml
routes:
  /professional/:
    controller: channel
    filter: tag:[pro,ux]
    data:
      post: page.professional
    order: published_at desc
    template: pro

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
---

**If you can't see changes, it's possible to restart ghost**

`ghost restart`
