### ISSUE TITLE
Ghost Search not honoring routes.yaml

### ISSUE THREAD

**Issue by cmilanf** [godofredoninja/Mapache#116]
My Ghost blog always had the post URL structure: `/{year}/{month}/{day}/{slug}/`, something inherited from old versions. Now, after upgrading to Ghost 3.1.1, I had to modify the `routes.yaml` in order to keep the same URLs, so it looks like:

```yaml
routes:

collections:
  /:
    permalink: /{year}/{month}/{day}/{slug}/

    template:
      # - godo-home-blog
      # - godo-home-travel
      # - godo-home-travel-featured
      # - godo-home-fashion-concept
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

The problem is that the search box results is not honoring the permalink defined there. Is this related to the theme or to the Ghost Search itself?
