### ISSUE TITLE
How to create /archive/ page with all posts?

### ISSUE THREAD

**Issue by calvinpark** [godofredoninja/Mapache#150]
Great theme!

I see a way to create archive pages for tags and authors. Is there a way to make a page to show show all posts?

I've tried this but `/archive/` shows an empty body with just header and footer

```
routes:
  /archive/:
    controller: channel
    template: godo-template-category

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
