### ISSUE TITLE
Log in and Sign Up give 404 errors

### ISSUE THREAD

**Issue by psharma04** [godofredoninja/Mapache#169]
Set up routes correctly, but neither of them work. Also tried going to [/members/signup](https://mysupport.lgbt/members/signup/) and [/members/signin](https://mysupport.lgbt/members/signin/), but neither seems to work.
Using Ghost 4.3.3.

Site with the issue: [https://mysupport.lgbt/](https://mysupport.lgbt/)

**Comment by bahola** [comment]
Hi,
How did you sort this out. I have the same problem

**Comment by softhints** [comment]
Hey,

I'm not sure if this is the correct solution but with latest ghost 4.8.4 you can try:
* ghost/#/settings (Settings)
* Membership
* Portal Settings
* Links

Find what are your links for Sign In and Sign Up

Then change the routes.yaml
* Settings
* Routes
* Download your file

Change it to:

```
routes:
  /signup/: members/signup
  /signin/: members/signin

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```


Note: I have two ghost versions and mapache and the steps differs for them. The above is for the latest one only:
* https://datascientyst.com/
* https://blog.softhints.com/
