### ISSUE TITLE
Unordered lists indented within a ordered list get the order list style applied.

### ISSUE THREAD

**Issue by TravisEz13** [godofredoninja/Mapache#92]
I tried casper, massively, and Ghostium and none of them have the issue.

The post in written in Markdown, but I'm not sure if that matters.

Here is the inspection:
![image](https://user-images.githubusercontent.com/10873629/52248184-0bd78f00-28a2-11e9-8eda-55316b6f9a32.png)
Here is the HTML:
![image](https://user-images.githubusercontent.com/10873629/52248208-26116d00-28a2-11e9-92aa-39708fcd5383.png)

The markdown looks like this
```markdown
1. foo
   * We have used this
```

**Comment by TravisEz13** [comment]
I worked around this by changing the css from

```css
.post-inner ol li:before{content:counter(post) ".";counter-increment:post;padding-right:12px}
```
to

```css
.post-inner ol > li:before{content:counter(post) ".";counter-increment:post;padding-right:12px}
```
